#!/usr/bin/python3

from plano import *

port = str(random_port())

ENV["MESSAGING_SERVICE_PORT"] = port

set_message_threshold("debug")

broker = None
worker_1 = None
worker_2 = None

try:
    broker = start_process("scripts/test-broker localhost {}", port)

    call_and_print_on_error("make clean build")
    worker_1 = start_process("make run-worker-1")
    worker_2 = start_process("make run-worker-2")

    call("make run-frontend")
except KeyboardInterrupt:
    pass
except CalledProcessError:
    terminate_process(broker)
    terminate_process(worker_1)
    terminate_process(worker_2)
